# Generated by Django 3.2.4 on 2021-06-06 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrossDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_a', models.CharField(max_length=100)),
                ('user_b', models.CharField(max_length=100)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrossDiaryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('feeling', models.CharField(choices=[('joy', '기쁨'), ('angry', '화남'), ('sad', '슬픔'), ('fear', '두려움')], default='joy', max_length=20)),
                ('date', models.DateField()),
                ('content', models.TextField(blank=True, null=True)),
                ('cross', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross', to='crossdiaryapp.crossdiary')),
            ],
            options={
                'unique_together': {('cross', 'date')},
            },
        ),
    ]
